### PR TITLE
create not-found page

### LINKED ISSUE #38: Not Found page

### PR DESCRIPTION
**Pull request by nuriyealp**
## Description

I created a 404 not-found page
## Related Issue
closes #38 

## Acceptance Criteria
The page contains a text and a link that return you back to a home page.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### After
Screen Shot 2022-12-04 at 8 05 41 PM

### CODE REVIEW

**Review by XeniyaDob — APPROVED** [review]
Good job

**Comment by elenamagay** [comment]
I think an image will help this page look more polished and full. In my opinion, this page should look similar to wireframes I created on Miro. One of the ideas for the image is a crying baby with a chef's hat on his head, with a ladle in his hand.

**Comment by nuriyealp** [comment]
@elenamagay thank you so much for your advice. I checked the wireframe and  I added the picture.

**Review by elenamagay — APPROVED** [review]
Looks great! Love the picture lol

**Pull request merged**
