### PR TITLE
remove padding on the sides

### PR DESCRIPTION
**Pull request by nuriyealp**
## Description

Added CSS to remove empty spaces on the sides

!!! This was missed when solving a merge conflict before. We needed to add it.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓  | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Review by XeniyaDob — APPROVED** [review]
Good job!

**Review by elenamagay — CHANGES_REQUESTED** [review]
If you scroll down you'll see a white gap there

**Comment by nuriyealp** [comment]
@elenamagay thank you so much! I deleted the gap.

**Review by elenamagay — APPROVED** [review]
Now I see why you had theme in props before :)

**Pull request merged**
