### PR TITLE
Create a myprofile page

### LINKED ISSUE #64: As a developer create the the users My profile page

### PR DESCRIPTION
**Pull request by nuriyealp**
## Description

Show Name, Email, and ability to change password.
## Resouce links or research articles

https://github.com/mui/material-ui/blob/v5.10.14/docs/data/material/getting-started/templates/sign-in/SignIn.js
## Related Issue
closes  #64 

## Acceptance Criteria
It should show the Name, Email, and ability to change the password.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### After
Screen Shot 2022-11-24 at 8 26 32 PM
Screen Shot 2022-11-24 at 8 26 45 PM

## Testing Steps / QA Criteria

- Click the Edit Account
- Click the Save

- Click change password
- Enter the old password after the new password and Confirm the password. And then save it.

### CODE REVIEW

**Review by XeniyaDob — APPROVED** [review]
Looks good for a start!

**Comment by elenamagay** [comment]
Works great. I think it would be better if on the change password page you change 
1. the name from "Password" to "Current Password" or "Old Password";
2. the name from "Confirm Password" to "Confirm New Password"
Otherwise, it confuses a bit

**Comment by nuriyealp** [comment]
@elenamagay thank you. This makes sense, I changed the names.

**Review by elenamagay — APPROVED** [review]
Ok, looks good now!

**Pull request merged**
