### PR TITLE
Login login dev

### LINKED ISSUE #8: create login screen and signup screen

### LINKED ISSUE #20: As a developer we need MUI installed in our app.

### LINKED ISSUE #23: update the README file with the App Name and Logo and description

### PR DESCRIPTION
**Pull request by nuriyealp**
## Description

Built sign-in form
Update name,logo,description
install material UI

## Resouce links or research articles

similar sign-in page from the material UI
https://mui.com/material-ui/getting-started/templates/sign-in/

## Related Issue
closes #8 
closes #20 
closes #23

## Acceptance Criteria
Need to create fields for UserName and Password and a Submit Button.
This is just a form layout.
Check the MUI API and get it working on the app

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    ✓ | :link: Update dependencies |
|    | :scroll: Docs              |

### After
Screen Shot 2022-10-25 at 9 21 46 PM

### CODE REVIEW

**Review by XeniyaDob — APPROVED** [review]
Looks good to me.

**Comment by CodergirlVS** [comment]
This page doesnt have the Logo? Are you going to have a NavBar here?

**Review by CodergirlVS — COMMENTED** [review]
PR Looks good, Congrats on your 1st PR. Loved the way you used the template. 

I have noted some changes which you can incorporate about the mui theme.Thanks

**Review by elenamagay — APPROVED** [review]
Looks good to me

**Pull request merged**
