### PR TITLE
build a landing page

### LINKED ISSUE #40: As a developer I want to built a landing page

### PR DESCRIPTION
**Pull request by nuriyealp**
## Description

I built a landing page.

## Resouce links or research articles

https://github.com/mui/material-ui/blob/v5.10.11/docs/data/material/getting-started/templates/sign-in-side/SignInSide.js

## Related Issue

closes #40
## Acceptance Criteria
Have a text as an app name
have a description
have a picture
have a get started button

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### After
Screen Shot 2022-10-30 at 2 05 30 PM
Screen Shot 2022-10-30 at 2 14 56 PM

### CODE REVIEW

**Review by XeniyaDob — APPROVED** [review]
The UI looks perfect!

**Review by elenamagay — APPROVED** [review]
Looks beautiful. Good job Nuriye!

**Review by XeniyaDob — APPROVED** [review]
As I  see, everything looks good!

**Review by CodergirlVS — APPROVED** [review]
Looks good!

**Pull request merged**
